const bcrypt = require('bcryptjs');

/**
 * Adaptive work factor (bcrypt "cost"). Each +1 doubles expected time.
 * OWASP suggests at least 10; 12 is a common default for new systems.
 * The salt is generated by bcrypt and stored inside the returned hash string.
 */
const BCRYPT_COST = 12;

async function hashPassword(plaintext) {
  return bcrypt.hash(plaintext, BCRYPT_COST);
}

async function verifyPassword(plaintext, storedHash) {
  if (!storedHash || typeof storedHash !== 'string') return false;
  return bcrypt.compare(plaintext, storedHash);
}

module.exports = { hashPassword, verifyPassword, BCRYPT_COST };
